version: '3.4'

services:
  app:
    container_name: mern-amazonc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - app:/app/build/

volumes:
  app:
