const data = {
  products: [
    {
      name: 'Nike Air Jordans',
      slug: 'nike-air-jordans',
      category: 'Shoes',
      image: '/images/p1.jpg',
      price: 300,
      countInStock: 20,
      brand: 'Nike',
      rating: 5,
      numReviews: 15,
      description: 'shoes',
    },
    {
      name: 'Converse High Tops',
      slug: 'converse-high-tops',
      category: 'Shoes',
      image: '/images/p2.jpg',
      price: 300,
      countInStock: 20,
      brand: 'Nike',
      rating: 5,
      numReviews: 15,
      description: 'shoes',
    },
    {
      name: 'Adidas Stan Smiths',
      slug: 'adidas-stan-smiths',
      category: 'Shoes',
      image: '/images/p3.jpg',
      price: 300,
      countInStock: 20,
      brand: 'Nike',
      rating: 5,
      numReviews: 15,
      description: 'shoes',
    },
    {
      name: 'New Balance 550s',
      slug: 'new-balance-550',
      category: 'Shoes',
      image: '/images/p4.jpg',
      price: 300,
      countInStock: 20,
      brand: 'Nike',
      rating: 5,
      numReviews: 15,
      description: 'shoes',
    },
  ],
};

export default data;
